SELECT DISTINCT m.COMPANY

FROM MANUFACTURER m
JOIN PRODUCT p ON p.RECIPE_ID = m.RECIPE_ID
JOIN CATEGORY c ON c.WARE = p.WARE

JOIN MANUFACTURER m2 ON m.COMPANY = m2.COMPANY
JOIN PRODUCT p2 ON p2.RECIPE_ID = m2.RECIPE_ID
JOIN CATEGORY c2 ON c2.WARE = p2.WARE
WHERE c2.CLASS = c.CLASS AND c2.WARE <> c.WARE

ORDER BY m.COMPANY ASC